"""Excel output: one workbook, four sheets, idempotent upsert-by-date on daily_log.
                                                                                                                                                                                                                                                                                                                                                                          
  Preserves first_loaded_at across re-syncs; bumps last_updated_at when the row
  actually changes. Most recent day lands at row 2, so the last_updated_at cell                                                                                                                                                                                                                                                                                           
  for the newest day sits in the sheet's top-right corner — satisfying the spec                                                                                                                                                                                                                                                                                           
  while keeping `pd.read_excel(sheet_name='daily_log')` clean with no extra rows.                                                                                                                                                                                                                                                                                         
  """                                                                                                                                                                                                                                                                                                                                                                     
  from __future__ import annotations                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                          
  from datetime import datetime                                                                                                                                                                                                                                                                                                                                           
  from pathlib import Path
  from typing import Any                                                                                                                                                                                                                                                                                                                                                  
                  
  import pandas as pd
  from openpyxl import Workbook, load_workbook
  from openpyxl.styles import Font
  from openpyxl.utils.dataframe import dataframe_to_rows                                                                                                                                                                                                                                                                                                                  
   
  DAILY_COLUMNS: list[str] = [                                                                                                                                                                                                                                                                                                                                            
      "date",     
      "sleep_duration_hours",                                                                                                                                                                                                                                                                                                                                             
      "sleep_performance",
      "sleep_efficiency",                                                                                                                                                                                                                                                                                                                                                 
      "time_in_bed_hours",
      "deep_sleep_minutes",                                                                                                                                                                                                                                                                                                                                               
      "rem_sleep_minutes",
      "light_sleep_minutes",                                                                                                                                                                                                                                                                                                                                              
      "awake_minutes",
      "disturbances",                                                                                                                                                                                                                                                                                                                                                     
      "resting_heart_rate",
      "hrv_rmssd",
      "respiratory_rate",                                                                                                                                                                                                                                                                                                                                                 
      "recovery_score",
      "day_strain",                                                                                                                                                                                                                                                                                                                                                       
      "max_heart_rate",
      "average_heart_rate",                                                                                                                                                                                                                                                                                                                                               
      "calories_burned",
      "skin_temp_celsius",                                                                                                                                                                                                                                                                                                                                                
      "spo2_percent",                                                                                                                                                                                                                                                                                                                                                     
      "first_loaded_at",
      "last_updated_at",                                                                                                                                                                                                                                                                                                                                                  
  ]               

  RAW_SLEEP_COLUMNS: list[str] = [                                                                                                                                                                                                                                                                                                                                        
      "sleep_id",
      "start",                                                                                                                                                                                                                                                                                                                                                            
      "end",                                                                                                                                                                                                                                                                                                                                                              
      "timezone_offset",
      "nap",                                                                                                                                                                                                                                                                                                                                                              
      "score_state",
      "sleep_performance",                                                                                                                                                                                                                                                                                                                                                
      "sleep_consistency",
      "sleep_efficiency",                                                                                                                                                                                                                                                                                                                                                 
      "respiratory_rate",                                                                                                                                                                                                                                                                                                                                                 
      "total_in_bed_minutes",
      "total_awake_minutes",                                                                                                                                                                                                                                                                                                                                              
      "total_light_sleep_minutes",
      "total_slow_wave_sleep_minutes",                                                                                                                                                                                                                                                                                                                                    
      "total_rem_sleep_minutes",
      "disturbance_count",                                                                                                                                                                                                                                                                                                                                                
  ]               
                                                                                                                                                                                                                                                                                                                                                                          
  RAW_WORKOUT_COLUMNS: list[str] = [                                                                                                                                                                                                                                                                                                                                      
      "workout_id",
      "start",                                                                                                                                                                                                                                                                                                                                                            
      "end",      
      "timezone_offset",
      "sport_name",
      "score_state",
      "strain",                                                                                                                                                                                                                                                                                                                                                           
      "duration_minutes",
      "average_heart_rate",                                                                                                                                                                                                                                                                                                                                               
      "max_heart_rate",
      "kilojoule",
      "calories_burned",                                                                                                                                                                                                                                                                                                                                                  
      "distance_meter",
      "altitude_gain_meter",                                                                                                                                                                                                                                                                                                                                              
  ]                                                                                                                                                                                                                                                                                                                                                                       
   
                                                                                                                                                                                                                                                                                                                                                                          
  def _read_existing_daily_log(path: Path) -> dict[str, dict[str, Any]]:
      """Return {date_str: row_dict} for existing daily_log, or empty dict."""                                                                                                                                                                                                                                                                                            
      if not path.exists():                                                                                                                                                                                                                                                                                                                                               
          return {}
      try:                                                                                                                                                                                                                                                                                                                                                                
          df = pd.read_excel(path, sheet_name="daily_log")
      except (ValueError, KeyError):
          return {}                                                                                                                                                                                                                                                                                                                                                       
      out: dict[str, dict[str, Any]] = {}
      for _, row in df.iterrows():                                                                                                                                                                                                                                                                                                                                        
          key = str(row["date"])[:10]  # normalise to YYYY-MM-DD
          out[key] = row.to_dict()                                                                                                                                                                                                                                                                                                                                        
      return out                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _merge_daily(
      existing: dict[str, dict[str, Any]],
      new_rows: list[dict[str, Any]],
      now_iso: str,
  ) -> tuple[list[dict[str, Any]], int, int]:                                                                                                                                                                                                                                                                                                                             
      """Upsert new_rows into existing by date. Returns (merged_rows_sorted_desc, added, updated)."""                                                                                                                                                                                                                                                                     
      added = 0                                                                                                                                                                                                                                                                                                                                                           
      updated = 0                                                                                                                                                                                                                                                                                                                                                         
      merged = dict(existing)                                                                                                                                                                                                                                                                                                                                             
      for row in new_rows:                                                                                                                                                                                                                                                                                                                                                
          date_key = str(row["date"])[:10]
          if date_key in merged:                                                                                                                                                                                                                                                                                                                                          
              prior = merged[date_key]
              # Compare only biometric fields; ignore timestamp columns.                                                                                                                                                                                                                                                                                                  
              changed = any(                                                                                                                                                                                                                                                                                                                                              
                  _not_equal(prior.get(col), row.get(col))                                                                                                                                                                                                                                                                                                                
                  for col in DAILY_COLUMNS                                                                                                                                                                                                                                                                                                                                
                  if col not in ("first_loaded_at", "last_updated_at", "date")
              )                                                                                                                                                                                                                                                                                                                                                           
              if changed:
                  new_record = {**prior, **row}                                                                                                                                                                                                                                                                                                                           
                  new_record["first_loaded_at"] = prior.get("first_loaded_at") or now_iso
                  new_record["last_updated_at"] = now_iso                                                                                                                                                                                                                                                                                                                 
                  merged[date_key] = new_record
                  updated += 1                                                                                                                                                                                                                                                                                                                                            
              # else: no-op, preserve prior row verbatim
          else:                                                                                                                                                                                                                                                                                                                                                           
              row["first_loaded_at"] = now_iso
              row["last_updated_at"] = now_iso                                                                                                                                                                                                                                                                                                                            
              merged[date_key] = row
              added += 1                                                                                                                                                                                                                                                                                                                                                  
      rows_sorted = sorted(merged.values(), key=lambda r: str(r["date"]), reverse=True)
      return rows_sorted, added, updated                                                                                                                                                                                                                                                                                                                                  
                  
                                                                                                                                                                                                                                                                                                                                                                          
  def _not_equal(a: Any, b: Any) -> bool:
      """NaN-safe inequality."""
      if a is None and b is None:                                                                                                                                                                                                                                                                                                                                         
          return False
      # pandas often stores missing as float NaN                                                                                                                                                                                                                                                                                                                          
      try:                                                                                                                                                                                                                                                                                                                                                                
          if pd.isna(a) and pd.isna(b):
              return False                                                                                                                                                                                                                                                                                                                                                
      except (TypeError, ValueError):
          pass
      if isinstance(a, float) and isinstance(b, float):                                                                                                                                                                                                                                                                                                                   
          return abs(a - b) > 1e-6
      return a != b                                                                                                                                                                                                                                                                                                                                                       
                  
                                                                                                                                                                                                                                                                                                                                                                          
  def _write_sheet(wb: Workbook, name: str, columns: list[str], rows: list[dict[str, Any]]) -> None:
      if name in wb.sheetnames:                                                                                                                                                                                                                                                                                                                                           
          del wb[name]                                                                                                                                                                                                                                                                                                                                                    
      ws = wb.create_sheet(name)
      ws.append(columns)                                                                                                                                                                                                                                                                                                                                                  
      for cell in ws[1]:
          cell.font = Font(bold=True)                                                                                                                                                                                                                                                                                                                                     
      df = pd.DataFrame(rows, columns=columns) if rows else pd.DataFrame(columns=columns)
      for r in dataframe_to_rows(df, index=False, header=False):                                                                                                                                                                                                                                                                                                          
          ws.append(r)                                                                                                                                                                                                                                                                                                                                                    
      ws.freeze_panes = "A2"                                                                                                                                                                                                                                                                                                                                              
      for i, col in enumerate(columns, start=1):                                                                                                                                                                                                                                                                                                                          
          ws.column_dimensions[ws.cell(row=1, column=i).column_letter].width = max(14, len(col) + 2)
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def write_workbook(                                                                                                                                                                                                                                                                                                                                                     
      path: Path,                                                                                                                                                                                                                                                                                                                                                         
      daily_new: list[dict[str, Any]],
      raw_sleep: list[dict[str, Any]],
      raw_workouts: list[dict[str, Any]],                                                                                                                                                                                                                                                                                                                                 
      sync_info: dict[str, Any],
  ) -> dict[str, int]:                                                                                                                                                                                                                                                                                                                                                    
      """Write all sheets, returning counts for the log. Idempotent by date on daily_log."""                                                                                                                                                                                                                                                                              
      path.parent.mkdir(parents=True, exist_ok=True)                                                                                                                                                                                                                                                                                                                      
      now_iso = datetime.now().isoformat(timespec="seconds")                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
      existing_daily = _read_existing_daily_log(path)                                                                                                                                                                                                                                                                                                                     
      merged_daily, added, updated = _merge_daily(existing_daily, daily_new, now_iso)                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                          
      wb = load_workbook(path) if path.exists() else Workbook()
      # Clear the default sheet on a fresh workbook.                                                                                                                                                                                                                                                                                                                      
      if "Sheet" in wb.sheetnames and len(wb.sheetnames) == 1:                                                                                                                                                                                                                                                                                                            
          del wb["Sheet"]                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                          
      _write_sheet(wb, "daily_log", DAILY_COLUMNS, merged_daily)                                                                                                                                                                                                                                                                                                          
      _write_sheet(wb, "raw_sleep", RAW_SLEEP_COLUMNS, raw_sleep)
      _write_sheet(wb, "raw_workouts", RAW_WORKOUT_COLUMNS, raw_workouts)                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                          
      # ---- metadata sheet ----                                                                                                                                                                                                                                                                                                                                          
      if "metadata" in wb.sheetnames:                                                                                                                                                                                                                                                                                                                                     
          del wb["metadata"]                                                                                                                                                                                                                                                                                                                                              
      meta = wb.create_sheet("metadata")
      dates = [str(r["date"])[:10] for r in merged_daily]                                                                                                                                                                                                                                                                                                                 
      first_sync = existing_daily and min(
          (str(r.get("first_loaded_at")) for r in existing_daily.values() if r.get("first_loaded_at")),                                                                                                                                                                                                                                                                   
          default=now_iso,                                                                                                                                                                                                                                                                                                                                                
      ) or now_iso                                                                                                                                                                                                                                                                                                                                                        
      missing_days, missing_reasons = _detect_missing(merged_daily)                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                          
      rows = [                                                                                                                                                                                                                                                                                                                                                            
          ("Date of first sync", first_sync),                                                                                                                                                                                                                                                                                                                             
          ("Date of last sync", now_iso),                                                                                                                                                                                                                                                                                                                                 
          ("Total days captured", len(merged_daily)),
          ("Days with missing data", len(missing_days)),                                                                                                                                                                                                                                                                                                                  
          ("Missing dates", ", ".join(missing_days) if missing_days else ""),
          ("Missing reasons", "; ".join(f"{d}: {r}" for d, r in missing_reasons.items())),                                                                                                                                                                                                                                                                                
          ("Date range", f"{min(dates)} → {max(dates)}" if dates else ""),                                                                                                                                                                                                                                                                                                
          ("Rows added this sync", sync_info.get("added", added)),                                                                                                                                                                                                                                                                                                        
          ("Rows updated this sync", sync_info.get("updated", updated)),                                                                                                                                                                                                                                                                                                  
          ("Rate limit — limit", sync_info.get("rate_limit", {}).get("limit", "")),                                                                                                                                                                                                                                                                                       
          ("Rate limit — remaining", sync_info.get("rate_limit", {}).get("remaining", "")),                                                                                                                                                                                                                                                                               
          ("Rate limit — reset (sec)", sync_info.get("rate_limit", {}).get("reset", "")),                                                                                                                                                                                                                                                                                 
          ("Profile", sync_info.get("profile_summary", "")),                                                                                                                                                                                                                                                                                                              
      ]                                                                                                                                                                                                                                                                                                                                                                   
      meta.append(["field", "value"])                                                                                                                                                                                                                                                                                                                                     
      for cell in meta[1]:                                                                                                                                                                                                                                                                                                                                                
          cell.font = Font(bold=True)
      for row in rows:                                                                                                                                                                                                                                                                                                                                                    
          meta.append(list(row))                                                                                                                                                                                                                                                                                                                                          
      meta.column_dimensions["A"].width = 32
      meta.column_dimensions["B"].width = 60                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
      wb.save(path)
      return {"added": added, "updated": updated, "total": len(merged_daily)}                                                                                                                                                                                                                                                                                             
                  
                                                                                                                                                                                                                                                                                                                                                                          
  def _detect_missing(rows: list[dict[str, Any]]) -> tuple[list[str], dict[str, str]]:
      """Find date-range gaps + per-day columns that came back null."""                                                                                                                                                                                                                                                                                                   
      if not rows:                                                                                                                                                                                                                                                                                                                                                        
          return [], {}
      dates = sorted(str(r["date"])[:10] for r in rows)                                                                                                                                                                                                                                                                                                                   
      start = pd.to_datetime(dates[0])
      end = pd.to_datetime(dates[-1])                                                                                                                                                                                                                                                                                                                                     
      full = pd.date_range(start, end, freq="D").strftime("%Y-%m-%d").tolist()
      present = set(dates)                                                                                                                                                                                                                                                                                                                                                
      gap_days = [d for d in full if d not in present]
                                                                                                                                                                                                                                                                                                                                                                          
      reasons: dict[str, str] = {d: "no cycle data returned by API" for d in gap_days}                                                                                                                                                                                                                                                                                    
      # Flag rows where core metrics are null.                                                                                                                                                                                                                                                                                                                            
      critical = ["recovery_score", "day_strain", "sleep_performance"]                                                                                                                                                                                                                                                                                                    
      for r in rows:                                                                                                                                                                                                                                                                                                                                                      
          d = str(r["date"])[:10]                                                                                                                                                                                                                                                                                                                                         
          missing_fields = [c for c in critical if r.get(c) is None or _is_nan(r.get(c))]                                                                                                                                                                                                                                                                                 
          if missing_fields:                                                                                                                                                                                                                                                                                                                                              
              reasons.setdefault(d, f"missing fields: {', '.join(missing_fields)}")                                                                                                                                                                                                                                                                                       
      all_missing = sorted(reasons.keys())                                                                                                                                                                                                                                                                                                                                
      return all_missing, reasons
                                                                                                                                                                                                                                                                                                                                                                          
                  
  def _is_nan(v: Any) -> bool:                                                                                                                                                                                                                                                                                                                                            
      try:        
          return bool(pd.isna(v))
      except (TypeError, ValueError):
          return False                                                                                                                                                                                                                                                                                                                                                    
  
