                                                                                                                                                                                                                                                                                                                                                                          
  """Main entry: `python sync_whoop.py`.                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                          
  First run does OAuth and a full history pull. Subsequent runs do an incremental
  sync from (latest_date - 3 days) to now, so re-scored sleep/recovery is captured.                                                                                                                                                                                                                                                                                       
  """                                                                                                                                                                                                                                                                                                                                                                     
  from __future__ import annotations                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                          
  import os                                                                                                                                                                                                                                                                                                                                                               
  import sys
  import traceback                                                                                                                                                                                                                                                                                                                                                        
  from datetime import datetime, timedelta, timezone
  from pathlib import Path
  from typing import Any

  import pandas as pd                                                                                                                                                                                                                                                                                                                                                     
  from dotenv import load_dotenv
                                                                                                                                                                                                                                                                                                                                                                          
  from excel_writer import write_workbook
  from whoop_client import WhoopAPIError, WhoopClient
                                                                                                                                                                                                                                                                                                                                                                          
  ROOT = Path(__file__).parent
  ENV_PATH = ROOT / ".env"                                                                                                                                                                                                                                                                                                                                                
  DATA_PATH = ROOT / "data" / "flavia_whoop_data.xlsx"                                                                                                                                                                                                                                                                                                                    
  LOG_PATH = ROOT / "logs" / "sync_log.txt"
                                                                                                                                                                                                                                                                                                                                                                          
  # Pull a few extra days on every incremental sync — Whoop sometimes finalises                                                                                                                                                                                                                                                                                           
  # sleep scoring hours after the night ends.                                                                                                                                                                                                                                                                                                                             
  REFRESH_WINDOW_DAYS = 3                                                                                                                                                                                                                                                                                                                                                 
  # Max pull window for a first-time sync. Whoop free tier retains ~25 days;                                                                                                                                                                                                                                                                                              
  # paid accounts keep more, so cast a wide net and let the API return what it has.                                                                                                                                                                                                                                                                                       
  INITIAL_HISTORY_DAYS = 400                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _iso(dt: datetime) -> str:                                                                                                                                                                                                                                                                                                                                          
      return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _cycle_date(cycle: dict[str, Any]) -> str:                                                                                                                                                                                                                                                                                                                          
      # cycle.start is when the cycle began (typically your morning wake-up).                                                                                                                                                                                                                                                                                             
      # That calendar date is the "day" this cycle represents.                                                                                                                                                                                                                                                                                                            
      start = cycle.get("start")                                                                                                                                                                                                                                                                                                                                          
      if not start:                                                                                                                                                                                                                                                                                                                                                       
          return ""                                                                                                                                                                                                                                                                                                                                                       
      return start[:10]
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _ms_to_minutes(ms: Any) -> float | None:
      if ms is None:                                                                                                                                                                                                                                                                                                                                                      
          return None
      try:
          return round(float(ms) / 60000.0, 2)
      except (TypeError, ValueError):
          return None                                                                                                                                                                                                                                                                                                                                                     
   
                                                                                                                                                                                                                                                                                                                                                                          
  def _ms_to_hours(ms: Any) -> float | None:
      if ms is None:
          return None
      try:
          return round(float(ms) / 3600000.0, 3)
      except (TypeError, ValueError):                                                                                                                                                                                                                                                                                                                                     
          return None
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _kj_to_cal(kj: Any) -> float | None:
      if kj is None:                                                                                                                                                                                                                                                                                                                                                      
          return None
      try:
          return round(float(kj) / 4.184, 1)
      except (TypeError, ValueError):
          return None                                                                                                                                                                                                                                                                                                                                                     
   
                                                                                                                                                                                                                                                                                                                                                                          
  def _build_daily_rows(
      cycles: list[dict[str, Any]],
      sleeps: list[dict[str, Any]],
      recoveries: list[dict[str, Any]],                                                                                                                                                                                                                                                                                                                                   
  ) -> list[dict[str, Any]]:
      # Index recoveries by cycle_id; index the night's primary (non-nap) sleep by cycle day.                                                                                                                                                                                                                                                                             
      recovery_by_cycle = {r.get("cycle_id"): r for r in recoveries if r.get("cycle_id")}                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                          
      # For sleep: a "primary sleep" is the non-nap sleep whose end date equals the cycle's date                                                                                                                                                                                                                                                                          
      # (i.e. the night that precedes the cycle's waking day). Index by that date.                                                                                                                                                                                                                                                                                        
      primary_sleep_by_date: dict[str, dict[str, Any]] = {}                                                                                                                                                                                                                                                                                                               
      for s in sleeps:                                                                                                                                                                                                                                                                                                                                                    
          if s.get("nap"):                                                                                                                                                                                                                                                                                                                                                
              continue                                                                                                                                                                                                                                                                                                                                                    
          end = s.get("end", "")
          if not end:                                                                                                                                                                                                                                                                                                                                                     
              continue
          date_key = end[:10]
          # If multiple non-nap sleeps share a date, keep the longest one.
          prior = primary_sleep_by_date.get(date_key)                                                                                                                                                                                                                                                                                                                     
          if prior is None:                                                                                                                                                                                                                                                                                                                                               
              primary_sleep_by_date[date_key] = s                                                                                                                                                                                                                                                                                                                         
          else:                                                                                                                                                                                                                                                                                                                                                           
              def _dur(rec: dict[str, Any]) -> float:
                  return float(rec.get("score", {}).get("stage_summary", {}).get("total_in_bed_time_milli") or 0)                                                                                                                                                                                                                                                         
              if _dur(s) > _dur(prior):                                                                                                                                                                                                                                                                                                                                   
                  primary_sleep_by_date[date_key] = s                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                          
      rows: list[dict[str, Any]] = []                                                                                                                                                                                                                                                                                                                                     
      for cycle in cycles:
          date = _cycle_date(cycle)
          if not date:                                                                                                                                                                                                                                                                                                                                                    
              continue
          cycle_score = cycle.get("score") or {}                                                                                                                                                                                                                                                                                                                          
                  
          sleep = primary_sleep_by_date.get(date) or {}                                                                                                                                                                                                                                                                                                                   
          sleep_score = sleep.get("score") or {}
          stages = sleep_score.get("stage_summary") or {}                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                          
          rec = recovery_by_cycle.get(cycle.get("id")) or {}                                                                                                                                                                                                                                                                                                              
          rec_score = rec.get("score") or {}                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          
          in_bed_ms = stages.get("total_in_bed_time_milli")                                                                                                                                                                                                                                                                                                               
          awake_ms = stages.get("total_awake_time_milli")
          asleep_ms = None                                                                                                                                                                                                                                                                                                                                                
          if in_bed_ms is not None and awake_ms is not None:                                                                                                                                                                                                                                                                                                              
              asleep_ms = float(in_bed_ms) - float(awake_ms)
                                                                                                                                                                                                                                                                                                                                                                          
          rows.append({
              "date": date,                                                                                                                                                                                                                                                                                                                                               
              "sleep_duration_hours": _ms_to_hours(asleep_ms),
              "sleep_performance": sleep_score.get("sleep_performance_percentage"),                                                                                                                                                                                                                                                                                       
              "sleep_efficiency": sleep_score.get("sleep_efficiency_percentage"),
              "time_in_bed_hours": _ms_to_hours(in_bed_ms),                                                                                                                                                                                                                                                                                                               
              "deep_sleep_minutes": _ms_to_minutes(stages.get("total_slow_wave_sleep_time_milli")),
              "rem_sleep_minutes": _ms_to_minutes(stages.get("total_rem_sleep_time_milli")),                                                                                                                                                                                                                                                                              
              "light_sleep_minutes": _ms_to_minutes(stages.get("total_light_sleep_time_milli")),
              "awake_minutes": _ms_to_minutes(awake_ms),                                                                                                                                                                                                                                                                                                                  
              "disturbances": stages.get("disturbance_count"),                                                                                                                                                                                                                                                                                                            
              "resting_heart_rate": rec_score.get("resting_heart_rate"),                                                                                                                                                                                                                                                                                                  
              "hrv_rmssd": rec_score.get("hrv_rmssd_milli"),                                                                                                                                                                                                                                                                                                              
              "respiratory_rate": sleep_score.get("respiratory_rate"),
              "recovery_score": rec_score.get("recovery_score"),                                                                                                                                                                                                                                                                                                          
              "day_strain": cycle_score.get("strain"),
              "max_heart_rate": cycle_score.get("max_heart_rate"),                                                                                                                                                                                                                                                                                                        
              "average_heart_rate": cycle_score.get("average_heart_rate"),                                                                                                                                                                                                                                                                                                
              "calories_burned": _kj_to_cal(cycle_score.get("kilojoule")),                                                                                                                                                                                                                                                                                                
              "skin_temp_celsius": rec_score.get("skin_temp_celsius"),                                                                                                                                                                                                                                                                                                    
              "spo2_percent": rec_score.get("spo2_percentage"),                                                                                                                                                                                                                                                                                                           
          })                                                                                                                                                                                                                                                                                                                                                              
      return rows                                                                                                                                                                                                                                                                                                                                                         
                  
                                                                                                                                                                                                                                                                                                                                                                          
  def _flatten_sleep(sleeps: list[dict[str, Any]]) -> list[dict[str, Any]]:
      out: list[dict[str, Any]] = []                                                                                                                                                                                                                                                                                                                                      
      for s in sleeps:                                                                                                                                                                                                                                                                                                                                                    
          score = s.get("score") or {}
          stages = score.get("stage_summary") or {}                                                                                                                                                                                                                                                                                                                       
          out.append({
              "sleep_id": s.get("id"),
              "start": s.get("start"),                                                                                                                                                                                                                                                                                                                                    
              "end": s.get("end"),
              "timezone_offset": s.get("timezone_offset"),                                                                                                                                                                                                                                                                                                                
              "nap": s.get("nap"),                                                                                                                                                                                                                                                                                                                                        
              "score_state": s.get("score_state"),
              "sleep_performance": score.get("sleep_performance_percentage"),                                                                                                                                                                                                                                                                                             
              "sleep_consistency": score.get("sleep_consistency_percentage"),
              "sleep_efficiency": score.get("sleep_efficiency_percentage"),                                                                                                                                                                                                                                                                                               
              "respiratory_rate": score.get("respiratory_rate"),
              "total_in_bed_minutes": _ms_to_minutes(stages.get("total_in_bed_time_milli")),                                                                                                                                                                                                                                                                              
              "total_awake_minutes": _ms_to_minutes(stages.get("total_awake_time_milli")),
              "total_light_sleep_minutes": _ms_to_minutes(stages.get("total_light_sleep_time_milli")),                                                                                                                                                                                                                                                                    
              "total_slow_wave_sleep_minutes": _ms_to_minutes(stages.get("total_slow_wave_sleep_time_milli")),                                                                                                                                                                                                                                                            
              "total_rem_sleep_minutes": _ms_to_minutes(stages.get("total_rem_sleep_time_milli")),                                                                                                                                                                                                                                                                        
              "disturbance_count": stages.get("disturbance_count"),                                                                                                                                                                                                                                                                                                       
          })                                                                                                                                                                                                                                                                                                                                                              
      return out  
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _flatten_workouts(workouts: list[dict[str, Any]]) -> list[dict[str, Any]]:
      out: list[dict[str, Any]] = []                                                                                                                                                                                                                                                                                                                                      
      for w in workouts:
          score = w.get("score") or {}
          start = w.get("start")
          end = w.get("end")
          duration_min: float | None = None                                                                                                                                                                                                                                                                                                                               
          if start and end:
              try:                                                                                                                                                                                                                                                                                                                                                        
                  s_dt = datetime.fromisoformat(start.replace("Z", "+00:00"))
                  e_dt = datetime.fromisoformat(end.replace("Z", "+00:00"))                                                                                                                                                                                                                                                                                               
                  duration_min = round((e_dt - s_dt).total_seconds() / 60.0, 1)                                                                                                                                                                                                                                                                                           
              except ValueError:                                                                                                                                                                                                                                                                                                                                          
                  duration_min = None                                                                                                                                                                                                                                                                                                                                     
          out.append({
              "workout_id": w.get("id"),                                                                                                                                                                                                                                                                                                                                  
              "start": start,
              "end": end,
              "timezone_offset": w.get("timezone_offset"),
              "sport_name": w.get("sport_name"),                                                                                                                                                                                                                                                                                                                          
              "score_state": w.get("score_state"),
              "strain": score.get("strain"),                                                                                                                                                                                                                                                                                                                              
              "duration_minutes": duration_min,
              "average_heart_rate": score.get("average_heart_rate"),                                                                                                                                                                                                                                                                                                      
              "max_heart_rate": score.get("max_heart_rate"),                                                                                                                                                                                                                                                                                                              
              "kilojoule": score.get("kilojoule"),
              "calories_burned": _kj_to_cal(score.get("kilojoule")),                                                                                                                                                                                                                                                                                                      
              "distance_meter": score.get("distance_meter"),                                                                                                                                                                                                                                                                                                              
              "altitude_gain_meter": score.get("altitude_gain_meter"),
          })                                                                                                                                                                                                                                                                                                                                                              
      return out  
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _determine_window(existing_path: Path) -> tuple[str | None, str]:
      now = datetime.now(timezone.utc)                                                                                                                                                                                                                                                                                                                                    
      if existing_path.exists():
          try:                                                                                                                                                                                                                                                                                                                                                            
              df = pd.read_excel(existing_path, sheet_name="daily_log")
              if not df.empty:                                                                                                                                                                                                                                                                                                                                            
                  latest = pd.to_datetime(df["date"]).max()
                  start_dt = (latest - timedelta(days=REFRESH_WINDOW_DAYS)).to_pydatetime()                                                                                                                                                                                                                                                                               
                  start_dt = start_dt.replace(tzinfo=timezone.utc, hour=0, minute=0, second=0, microsecond=0)                                                                                                                                                                                                                                                             
                  return _iso(start_dt), _iso(now)                                                                                                                                                                                                                                                                                                                        
          except (ValueError, KeyError):                                                                                                                                                                                                                                                                                                                                  
              pass                                                                                                                                                                                                                                                                                                                                                        
      # First run: cast a wide net and let Whoop return whatever it retains.
      start_dt = now - timedelta(days=INITIAL_HISTORY_DAYS)                                                                                                                                                                                                                                                                                                               
      return _iso(start_dt), _iso(now)                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def _append_log(message: str) -> None:
      LOG_PATH.parent.mkdir(parents=True, exist_ok=True)                                                                                                                                                                                                                                                                                                                  
      ts = datetime.now().isoformat(timespec="seconds")
      with LOG_PATH.open("a") as f:                                                                                                                                                                                                                                                                                                                                       
          f.write(f"[{ts}] {message}\n")
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  def main() -> int:
      load_dotenv(ENV_PATH)                                                                                                                                                                                                                                                                                                                                               
      client_id = os.getenv("WHOOP_CLIENT_ID", "").strip()
      client_secret = os.getenv("WHOOP_CLIENT_SECRET", "").strip()                                                                                                                                                                                                                                                                                                        
      redirect_uri = os.getenv("WHOOP_REDIRECT_URI", "http://localhost:8645/callback").strip()
      refresh_token = os.getenv("WHOOP_REFRESH_TOKEN", "").strip()                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
      if not client_id or not client_secret:                                                                                                                                                                                                                                                                                                                              
          print("ERROR: WHOOP_CLIENT_ID and WHOOP_CLIENT_SECRET must be set in .env", file=sys.stderr)                                                                                                                                                                                                                                                                    
          print("Copy .env.example to .env and fill in credentials from developer.whoop.com.", file=sys.stderr)                                                                                                                                                                                                                                                           
          return 2                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
      client = WhoopClient(                                                                                                                                                                                                                                                                                                                                               
          client_id=client_id,
          client_secret=client_secret,                                                                                                                                                                                                                                                                                                                                    
          redirect_uri=redirect_uri,
          refresh_token=refresh_token or None,
          env_path=ENV_PATH,
      )                                                                                                                                                                                                                                                                                                                                                                   
  
      try:                                                                                                                                                                                                                                                                                                                                                                
          if not refresh_token:
              print("No refresh token found — starting OAuth flow.")
              client.run_oauth_flow()                                                                                                                                                                                                                                                                                                                                     
              print("OAuth complete. Refresh token saved to .env.")
                                                                                                                                                                                                                                                                                                                                                                          
          start, end = _determine_window(DATA_PATH)                                                                                                                                                                                                                                                                                                                       
          mode = "incremental" if DATA_PATH.exists() else "initial"                                                                                                                                                                                                                                                                                                       
          print(f"Sync mode: {mode}. Window: {start} → {end}")                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                          
          print("Fetching cycles…")                                                                                                                                                                                                                                                                                                                                       
          cycles = client.list_cycles(start, end)                                                                                                                                                                                                                                                                                                                         
          print(f"  {len(cycles)} cycles")
                                                                                                                                                                                                                                                                                                                                                                          
          print("Fetching sleep…")
          sleeps = client.list_sleep(start, end)                                                                                                                                                                                                                                                                                                                          
          print(f"  {len(sleeps)} sleep records")
                                                                                                                                                                                                                                                                                                                                                                          
          print("Fetching recovery…")
          recoveries = client.list_recovery(start, end)                                                                                                                                                                                                                                                                                                                   
          print(f"  {len(recoveries)} recoveries")
                                                                                                                                                                                                                                                                                                                                                                          
          print("Fetching workouts…")
          workouts = client.list_workouts(start, end)                                                                                                                                                                                                                                                                                                                     
          print(f"  {len(workouts)} workouts")
                                                                                                                                                                                                                                                                                                                                                                          
          try:
              profile = client.get_profile()                                                                                                                                                                                                                                                                                                                              
              profile_summary = f"{profile.get('first_name', '')} {profile.get('last_name', '')}".strip() or profile.get("email", "")
          except WhoopAPIError:                                                                                                                                                                                                                                                                                                                                           
              profile_summary = ""
                                                                                                                                                                                                                                                                                                                                                                          
          daily_rows = _build_daily_rows(cycles, sleeps, recoveries)
          raw_sleep_rows = _flatten_sleep(sleeps)                                                                                                                                                                                                                                                                                                                         
          raw_workout_rows = _flatten_workouts(workouts)                                                                                                                                                                                                                                                                                                                  
  
          sync_info = {                                                                                                                                                                                                                                                                                                                                                   
              "rate_limit": getattr(client, "last_rate_limit", {}),
              "profile_summary": profile_summary,                                                                                                                                                                                                                                                                                                                         
          }                                                                                                                                                                                                                                                                                                                                                               
          result = write_workbook(DATA_PATH, daily_rows, raw_sleep_rows, raw_workout_rows, sync_info)
                                                                                                                                                                                                                                                                                                                                                                          
          msg = ( 
              f"mode={mode} pulled_cycles={len(cycles)} sleep={len(sleeps)} "                                                                                                                                                                                                                                                                                             
              f"recovery={len(recoveries)} workouts={len(workouts)} "                                                                                                                                                                                                                                                                                                     
              f"added={result['added']} updated={result['updated']} total_days={result['total']} "                                                                                                                                                                                                                                                                        
              f"rate_remaining={sync_info['rate_limit'].get('remaining')}"                                                                                                                                                                                                                                                                                                
          )                                                                                                                                                                                                                                                                                                                                                               
          _append_log(msg)                                                                                                                                                                                                                                                                                                                                                
          if result["added"] == 0 and result["updated"] == 0:                                                                                                                                                                                                                                                                                                             
              print("No new or changed data.")
          else:                                                                                                                                                                                                                                                                                                                                                           
              print(f"Saved: {DATA_PATH}")
              print(f"  +{result['added']} new day(s), {result['updated']} updated, {result['total']} total")                                                                                                                                                                                                                                                             
          return 0                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
      except WhoopAPIError as e:                                                                                                                                                                                                                                                                                                                                          
          err = f"WhoopAPIError: {e}"
          print(err, file=sys.stderr)                                                                                                                                                                                                                                                                                                                                     
          _append_log(err)
          return 1                                                                                                                                                                                                                                                                                                                                                        
      except Exception as e:  # noqa: BLE001
          err = f"Unhandled error: {e}\n{traceback.format_exc()}"                                                                                                                                                                                                                                                                                                         
          print(err, file=sys.stderr)
          _append_log(err)                                                                                                                                                                                                                                                                                                                                                
          return 1
                                                                                                                                                                                                                                                                                                                                                                          
                  
  if __name__ == "__main__":
      sys.exit(main())
