"""Whoop API v2 client: OAuth 2.0 authorization code flow + paginated data pulls.
                                                                                                                                                                                                                                                                                                                                                                          
  On first run, run_oauth_flow() opens a browser, captures the ?code= redirect on
  localhost, exchanges it for tokens, and writes the refresh token back to .env.                                                                                                                                                                                                                                                                                          
  Subsequent runs use the stored refresh token.
  """                                                                                                                                                                                                                                                                                                                                                                     
  from __future__ import annotations
                                                                                                                                                                                                                                                                                                                                                                          
  import http.server
  import secrets
  import socketserver
  import threading
  import time
  import urllib.parse
  import webbrowser
  from dataclasses import dataclass
  from pathlib import Path
  from typing import Any, Iterator
                                                                                                                                                                                                                                                                                                                                                                          
  import requests
                                                                                                                                                                                                                                                                                                                                                                          
  API_BASE = "https://api.prod.whoop.com"
  AUTH_URL = f"{API_BASE}/oauth/oauth2/auth"
  TOKEN_URL = f"{API_BASE}/oauth/oauth2/token"
                                                                                                                                                                                                                                                                                                                                                                          
  SCOPES = [
      "read:recovery",                                                                                                                                                                                                                                                                                                                                                    
      "read:cycles",
      "read:workout",
      "read:sleep",                                                                                                                                                                                                                                                                                                                                                       
      "read:profile",
      "read:body_measurement",                                                                                                                                                                                                                                                                                                                                            
      "offline",  
  ]                                                                                                                                                                                                                                                                                                                                                                       
   
  # Page size cap documented by Whoop (v2 list endpoints).                                                                                                                                                                                                                                                                                                                
  PAGE_LIMIT = 25 
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          
  class WhoopAPIError(Exception):
      """Raised for non-retryable Whoop API responses."""                                                                                                                                                                                                                                                                                                                 
                  

  @dataclass
  class Tokens:
      access_token: str                                                                                                                                                                                                                                                                                                                                                   
      refresh_token: str
      expires_at: float  # unix seconds                                                                                                                                                                                                                                                                                                                                   
                  
                                                                                                                                                                                                                                                                                                                                                                          
  class WhoopClient:
      def __init__(                                                                                                                                                                                                                                                                                                                                                       
          self,   
          client_id: str,
          client_secret: str,
          redirect_uri: str,
          refresh_token: str | None = None,
          env_path: Path | None = None,
      ) -> None:                                                                                                                                                                                                                                                                                                                                                          
          self.client_id = client_id
          self.client_secret = client_secret                                                                                                                                                                                                                                                                                                                              
          self.redirect_uri = redirect_uri
          self.env_path = env_path
          self._tokens: Tokens | None = None                                                                                                                                                                                                                                                                                                                              
          if refresh_token:
              # We have a stored refresh token; get a fresh access token before use.                                                                                                                                                                                                                                                                                      
              self._tokens = Tokens(access_token="", refresh_token=refresh_token, expires_at=0)                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                          
      # ---------------- OAuth ----------------                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                          
      def run_oauth_flow(self) -> Tokens:                                                                                                                                                                                                                                                                                                                                 
          """Interactive: opens browser, runs a one-shot localhost server, returns tokens."""
          state = secrets.token_urlsafe(16)                                                                                                                                                                                                                                                                                                                               
          params = {                                                                                                                                                                                                                                                                                                                                                      
              "response_type": "code",                                                                                                                                                                                                                                                                                                                                    
              "client_id": self.client_id,                                                                                                                                                                                                                                                                                                                                
              "redirect_uri": self.redirect_uri,
              "scope": " ".join(SCOPES),
              "state": state,                                                                                                                                                                                                                                                                                                                                             
          }
          auth_url = f"{AUTH_URL}?{urllib.parse.urlencode(params)}"                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                          
          parsed = urllib.parse.urlparse(self.redirect_uri)
          host = parsed.hostname or "localhost"                                                                                                                                                                                                                                                                                                                           
          port = parsed.port or 8645                                                                                                                                                                                                                                                                                                                                      
          captured: dict[str, str] = {}
                                                                                                                                                                                                                                                                                                                                                                          
          class Handler(http.server.BaseHTTPRequestHandler):                                                                                                                                                                                                                                                                                                              
              def log_message(self, *_: Any) -> None:  # silence default logs
                  return                                                                                                                                                                                                                                                                                                                                                  
                  
              def do_GET(self) -> None:  # noqa: N802                                                                                                                                                                                                                                                                                                                     
                  qs = urllib.parse.urlparse(self.path).query
                  q = urllib.parse.parse_qs(qs)                                                                                                                                                                                                                                                                                                                           
                  if "code" in q and q.get("state", [""])[0] == state:
                      captured["code"] = q["code"][0]                                                                                                                                                                                                                                                                                                                     
                      self.send_response(200)
                      self.send_header("Content-Type", "text/html; charset=utf-8")                                                                                                                                                                                                                                                                                        
                      self.end_headers()
                      self.wfile.write(b"<h2>Whoop auth complete. You can close this tab.</h2>")                                                                                                                                                                                                                                                                          
                  else:                                                                                                                                                                                                                                                                                                                                                   
                      self.send_response(400)
                      self.end_headers()                                                                                                                                                                                                                                                                                                                                  
                      self.wfile.write(b"Auth failed or state mismatch.")
                                                                                                                                                                                                                                                                                                                                                                          
          with socketserver.TCPServer((host, port), Handler) as httpd:                                                                                                                                                                                                                                                                                                    
              print(f"Opening browser for Whoop OAuth. If it doesn't open, visit:\n{auth_url}\n")                                                                                                                                                                                                                                                                         
              webbrowser.open(auth_url)                                                                                                                                                                                                                                                                                                                                   
              thread = threading.Thread(target=httpd.serve_forever, daemon=True)
              thread.start()                                                                                                                                                                                                                                                                                                                                              
              # Wait for the redirect handler to capture a code.
              while "code" not in captured:                                                                                                                                                                                                                                                                                                                               
                  time.sleep(0.2)                                                                                                                                                                                                                                                                                                                                         
              httpd.shutdown()
                                                                                                                                                                                                                                                                                                                                                                          
          tokens = self._exchange_code(captured["code"])                                                                                                                                                                                                                                                                                                                  
          self._tokens = tokens
          self._persist_refresh_token(tokens.refresh_token)                                                                                                                                                                                                                                                                                                               
          return tokens                                                                                                                                                                                                                                                                                                                                                   
   
      def _exchange_code(self, code: str) -> Tokens:                                                                                                                                                                                                                                                                                                                      
          resp = requests.post(
              TOKEN_URL,
              data={                                                                                                                                                                                                                                                                                                                                                      
                  "grant_type": "authorization_code",
                  "code": code,                                                                                                                                                                                                                                                                                                                                           
                  "client_id": self.client_id,
                  "client_secret": self.client_secret,
                  "redirect_uri": self.redirect_uri,
              },                                                                                                                                                                                                                                                                                                                                                          
              headers={"Content-Type": "application/x-www-form-urlencoded"},
              timeout=30,                                                                                                                                                                                                                                                                                                                                                 
          )       
          resp.raise_for_status()
          return self._tokens_from_response(resp.json())                                                                                                                                                                                                                                                                                                                  
   
      def _refresh(self) -> Tokens:                                                                                                                                                                                                                                                                                                                                       
          if not self._tokens or not self._tokens.refresh_token:
              raise WhoopAPIError("No refresh token available. Run OAuth flow first.")                                                                                                                                                                                                                                                                                    
          resp = requests.post(                                                                                                                                                                                                                                                                                                                                           
              TOKEN_URL,
              data={                                                                                                                                                                                                                                                                                                                                                      
                  "grant_type": "refresh_token",
                  "refresh_token": self._tokens.refresh_token,
                  "client_id": self.client_id,                                                                                                                                                                                                                                                                                                                            
                  "client_secret": self.client_secret,
                  "scope": " ".join(SCOPES),                                                                                                                                                                                                                                                                                                                              
              },  
              headers={"Content-Type": "application/x-www-form-urlencoded"},
              timeout=30,                                                                                                                                                                                                                                                                                                                                                 
          )
          if resp.status_code >= 400:                                                                                                                                                                                                                                                                                                                                     
              raise WhoopAPIError(f"Token refresh failed: {resp.status_code} {resp.text}")
          tokens = self._tokens_from_response(resp.json())                                                                                                                                                                                                                                                                                                                
          self._tokens = tokens
          # Whoop rotates refresh tokens — persist the new one.                                                                                                                                                                                                                                                                                                           
          self._persist_refresh_token(tokens.refresh_token)                                                                                                                                                                                                                                                                                                               
          return tokens                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                          
      @staticmethod                                                                                                                                                                                                                                                                                                                                                       
      def _tokens_from_response(data: dict[str, Any]) -> Tokens:
          return Tokens(
              access_token=data["access_token"],                                                                                                                                                                                                                                                                                                                          
              refresh_token=data.get("refresh_token", ""),
              expires_at=time.time() + int(data.get("expires_in", 3600)) - 60,  # 1-min safety margin                                                                                                                                                                                                                                                                     
          )                                                                                                                                                                                                                                                                                                                                                               
   
      def _persist_refresh_token(self, refresh_token: str) -> None:                                                                                                                                                                                                                                                                                                       
          if not self.env_path or not refresh_token:
              return                                                                                                                                                                                                                                                                                                                                                      
          lines: list[str] = []
          found = False                                                                                                                                                                                                                                                                                                                                                   
          if self.env_path.exists():
              for line in self.env_path.read_text().splitlines():                                                                                                                                                                                                                                                                                                         
                  if line.startswith("WHOOP_REFRESH_TOKEN="):                                                                                                                                                                                                                                                                                                             
                      lines.append(f"WHOOP_REFRESH_TOKEN={refresh_token}")
                      found = True                                                                                                                                                                                                                                                                                                                                        
                  else:
                      lines.append(line)                                                                                                                                                                                                                                                                                                                                  
          if not found:
              lines.append(f"WHOOP_REFRESH_TOKEN={refresh_token}")
          self.env_path.write_text("\n".join(lines) + "\n")                                                                                                                                                                                                                                                                                                               
   
      def _ensure_access_token(self) -> str:                                                                                                                                                                                                                                                                                                                              
          if not self._tokens or time.time() >= self._tokens.expires_at:
              self._refresh()                                                                                                                                                                                                                                                                                                                                             
          assert self._tokens is not None
          return self._tokens.access_token                                                                                                                                                                                                                                                                                                                                
                  
      # ---------------- HTTP ----------------

      def _request(self, path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:                                                                                                                                                                                                                                                                              
          """GET with retry/backoff. Refreshes token on 401, respects 429."""
          url = f"{API_BASE}{path}"                                                                                                                                                                                                                                                                                                                                       
          attempt = 0
          while True:                                                                                                                                                                                                                                                                                                                                                     
              attempt += 1
              token = self._ensure_access_token()                                                                                                                                                                                                                                                                                                                         
              headers = {"Authorization": f"Bearer {token}"}
              try:
                  resp = requests.get(url, params=params, headers=headers, timeout=30)
              except requests.RequestException as e:                                                                                                                                                                                                                                                                                                                      
                  if attempt >= 5:
                      raise WhoopAPIError(f"Network error after {attempt} attempts: {e}") from e                                                                                                                                                                                                                                                                          
                  time.sleep(min(2 ** attempt, 30))                                                                                                                                                                                                                                                                                                                       
                  continue                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                          
              # Save the latest rate-limit snapshot on the client for metadata sheet.                                                                                                                                                                                                                                                                                     
              self.last_rate_limit = {
                  "limit": resp.headers.get("X-RateLimit-Limit"),                                                                                                                                                                                                                                                                                                         
                  "remaining": resp.headers.get("X-RateLimit-Remaining"),
                  "reset": resp.headers.get("X-RateLimit-Reset"),                                                                                                                                                                                                                                                                                                         
              }   
                                                                                                                                                                                                                                                                                                                                                                          
              if resp.status_code == 401 and attempt == 1:                                                                                                                                                                                                                                                                                                                
                  # Access token may have been revoked server-side — force refresh.
                  self._tokens = Tokens(                                                                                                                                                                                                                                                                                                                                  
                      access_token="",
                      refresh_token=self._tokens.refresh_token if self._tokens else "",                                                                                                                                                                                                                                                                                   
                      expires_at=0,                                                                                                                                                                                                                                                                                                                                       
                  )
                  continue                                                                                                                                                                                                                                                                                                                                                
              if resp.status_code == 429:
                  retry_after = int(resp.headers.get("Retry-After", "0")) or min(2 ** attempt, 60)                                                                                                                                                                                                                                                                        
                  time.sleep(retry_after)                                                                                                                                                                                                                                                                                                                                 
                  continue                                                                                                                                                                                                                                                                                                                                                
              if 500 <= resp.status_code < 600:                                                                                                                                                                                                                                                                                                                           
                  if attempt >= 5:
                      raise WhoopAPIError(f"{resp.status_code} from {path}: {resp.text[:200]}")                                                                                                                                                                                                                                                                           
                  time.sleep(min(2 ** attempt, 30))                                                                                                                                                                                                                                                                                                                       
                  continue                                                                                                                                                                                                                                                                                                                                                
              if resp.status_code >= 400:                                                                                                                                                                                                                                                                                                                                 
                  raise WhoopAPIError(f"{resp.status_code} from {path}: {resp.text[:200]}")
              return resp.json()                                                                                                                                                                                                                                                                                                                                          
   
      def _paginate(self, path: str, start: str | None, end: str | None) -> Iterator[dict[str, Any]]:                                                                                                                                                                                                                                                                     
          next_token: str | None = None
          while True:                                                                                                                                                                                                                                                                                                                                                     
              params: dict[str, Any] = {"limit": PAGE_LIMIT}
              if start:                                                                                                                                                                                                                                                                                                                                                   
                  params["start"] = start
              if end:                                                                                                                                                                                                                                                                                                                                                     
                  params["end"] = end
              if next_token:                                                                                                                                                                                                                                                                                                                                              
                  params["nextToken"] = next_token
              data = self._request(path, params=params)
              for rec in data.get("records", []):                                                                                                                                                                                                                                                                                                                         
                  yield rec
              next_token = data.get("next_token")                                                                                                                                                                                                                                                                                                                         
              if not next_token:
                  return
                                                                                                                                                                                                                                                                                                                                                                          
      # ---------------- Public API methods ----------------
                                                                                                                                                                                                                                                                                                                                                                          
      def get_profile(self) -> dict[str, Any]:
          return self._request("/developer/v2/user/profile/basic")
                                                                                                                                                                                                                                                                                                                                                                          
      def list_cycles(self, start: str | None, end: str | None) -> list[dict[str, Any]]:                                                                                                                                                                                                                                                                                  
          return list(self._paginate("/developer/v2/cycle", start, end))                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                          
      def list_sleep(self, start: str | None, end: str | None) -> list[dict[str, Any]]:
          return list(self._paginate("/developer/v2/activity/sleep", start, end))                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                          
      def list_recovery(self, start: str | None, end: str | None) -> list[dict[str, Any]]:
          return list(self._paginate("/developer/v2/recovery", start, end))                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                          
      def list_workouts(self, start: str | None, end: str | None) -> list[dict[str, Any]]:
          return list(self._paginate("/developer/v2/activity/workout", start, end))   
